#!/usr/bin/env bash
# Installs nginx web server

# update package list and upgrade packages
sudo apt-get update
sudo apt-get -y upgrade

# install Nginx
sudo apt-get -y install nginx

sudo chown -R "$USER":"$USER" /var/www/html

sudo chmod -R 755 /var/www

# create the "Hello World!" page
echo "Hello World!" > /var/www/html/index.html

# configure Nginx to listen on port 80
sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default

# restart Nginx
sudo service nginx restart
